const service = {
    signup: 'users/signup',
    activiationEmail: 'users/activiationEmail',
    signin: 'users/signin',
    resetPassOTP: 'users/resetPassOTP',
    resetPassword: 'users/resetPassword',
    walletAuth: 'users/walletAuth',
    getProfile: 'users/getUserProfile',
    profiledatas: 'users/profiledatas',
    changepassword: 'users/changePassword',
    getOTPMobileandEmail: 'users/getOTPMobileandEmail',
    editprofile: "users/editprofile",
    Resendotp: 'users/resendotp',
    updateProfile: 'users/updateProfile',
    uploadData: 'nft/minting',
    nftCreate: 'nft/nftCreate',
    getNFTDetails: 'nft/getNFTDetails',
    nftCategories: 'nft/nftCategories',
    nftsubCategories: 'nft/nftsubCategories',
    createCollection: 'nft/createCollection',
    getCollections: 'nft/getCollections',
    getownerProfile: 'users/getownerProfile',
    startAuction: 'nft/startAuction',
    getNFTS: 'nft/getNFTS',
    buyNFT: 'nft/buyNFT',
    getAuctionDetails: 'nft/getAuctionDetails',
    bidNFT: 'nft/bidNFT',
    startSale: 'nft/startSale',
    getnftbyCollections: 'nft/getnftbyCollections',
    userNFTS: 'nft/userNFTS',
    getdashboard: 'nft/dashboardData',
    getactivity: 'nft/userActivities',
    userCollections: 'nft/userCollections',
    getcollectionNFTS: 'nft/getcollectionNFTS',
    allCollections: 'nft/getallCollections',
    favoriteAction: 'nft/favoriteAction',
    getprivateNFTS: 'nft/getprivateNFTS',
    getauctionNFTS: 'nft/getauctionNFTS',
    endAuction: 'nft/endAuction',
    cancelAuction: 'nft/cancelAuction',
    bidWithdraw: 'nft/bidWithdraw',
    transferNFT: 'nft/transferNFT',
    followUser: 'nft/follow',
    getownProfile: 'nft/getownProfile',
    getuseractivity: 'nft/userActivity',
    getallActivity: 'nft/alluserActivity',
    userNotifications: 'nft/userNotifications',
    getusersProfile: 'nft/getusersProfile',
    likedNFTS: 'nft/likedNFTS',
    findNFTS: 'nft/findNFTS',
    mintNFT: 'nft/mintNFT',
    getallNFTS: 'nft/getallNFTS',
    lazystartSale: 'nft/lazystartSale',
    checkUser: 'users/check_user',
    movieCategories: 'nft/getmovieCategory',
    movieJoners: 'nft/getmovieJoner',
    createMovie: 'nft/movieCreate',
    getAllMovie: 'users/getAllMovies',
    getOneMovieById: (movieIdforUpdat) =>  `users/movie/${movieIdforUpdat}` ,
    updateMovie: 'nft/updateMovie',
    deleteMovie:'nft/deleteMovie',
    createJoner: 'nft/addmovieJoner',
    getAllJoner: 'nft/getmovieJoner',
    updateJoner: 'nft/updatemovieJoner',
    deleteJoner: 'nft/deletemovieJoner',
    createCategory: 'nft/addmovieCategory',
    getAllCategory: 'nft/getmovieCategory',
    updateCategory:'nft/updatemovieCategory',
    deleteCategory: 'nft/deletemovieCategory',

    createNftCategory: 'nft/addcategory',
    getNftCategory: 'nft/getCategory',
    deleteNftCategory:'nft/deleteCategory',
    updateNftCategory: 'nft/updateCategory',
    
    createNftCollection: 'nft/createCollection',
    getNftCollection: 'nft/getCollections',
    deleteNftCollection:'nft/deleteCollection',
    updateNftCollection: 'nft/updateCollection',
    
    getAllUsers: 'users/get_all_users_data',
    
    createRightsData:'movies/add_rights',
    getAllRights: (movieId) => `rights/movie/${movieId}` ,
}

export default service;